input:
  videos:
    - multiview-object-tracking-dataset/CAMPUS/Garden1/Video/view-IP1.mp4
    - multiview-object-tracking-dataset/CAMPUS/Garden1/Video/view-Contour2.mp4
    - multiview-object-tracking-dataset/CAMPUS/Garden1/Video/view-HC3.mp4
    - multiview-object-tracking-dataset/CAMPUS/Garden1/Video/view-HC2.mp4
  annotations:
    - data/track_cluster/campus_dataset/garden1/track/view-IP1.txt
    - data/track_cluster/campus_dataset/garden1/track/view-Contour2.txt
    - data/track_cluster/campus_dataset/garden1/track/view-HC3.txt
    - data/track_cluster/campus_dataset/garden1/track/view-HC2.txt
  task : postprocessing
output:
  size: [1920, 1080]
  output_dir: postprocessing/campus_dataset/video_output
  fps: 30